scene_0:
  name: "warehouse"
  render_offset: [0, 0, 0]

scene_1:
  name: "street"
  render_offset: [0, 0, 0]

scene_2:
  name: "forest"
  render_offset: [118, 201, 99]
  # render_offset: [148, 201, 104] generate point cloud

scene_3:
  name: "wasteland"
  render_offset: [1140, 1026, 108]